[versions]
agp = "8.1.0-beta04"
org-jetbrains-kotlin-android = "1.8.10"
core-ktx = "1.10.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
material = "1.9.0"
constraintlayout = "2.1.4"
timber = "5.0.1"
legacy-support-v4 = "1.0.0"
lifecycle-livedata-ktx = "2.6.1"
lifecycle-viewmodel-ktx = "2.6.1"
retrofit = "2.9.0"
glide = "4.15.1"
navigation = "2.6.0"
hilt = "2.46.1"
room = "2.5.1"
ksp = "1.8.10-1.0.9"
viewBinding = "1.5.9"
chucker = "3.5.2"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacy-support-v4" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle-livedata-ktx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }

timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofitGson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }

navigationFragments = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigationUi = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hiltKapt = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
roomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
roomCoroutines = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

viewBinding = { group = "com.github.kirich1409", name = "viewbindingpropertydelegate-noreflection", version.ref = "viewBinding" }

chuckerDebug = { group = "com.github.chuckerteam.chucker", name = "library", version.ref = "chucker" }
chuckerRelease = { group = "com.github.chuckerteam.chucker", name = "library-no-op", version.ref = "chucker" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
org-jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "org-jetbrains-kotlin-android" }
com-google-dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]

